# Generated by Django 4.1.5 on 2023-01-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('W', 'Wlasciciel'), ('K', 'Klient')], default='W', max_length=1),
        ),
    ]
