# Generated by Django 4.1.5 on 2023-01-21 12:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ceny',
            fields=[
                ('kat_cenowa', models.IntegerField(primary_key=True, serialize=False)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('haslo', models.CharField(max_length=30)),
                ('imie', models.CharField(max_length=30)),
                ('nazwisko', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Pokoj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=40)),
                ('kategoria', models.CharField(max_length=40)),
                ('trudnosc', models.IntegerField()),
                ('max_czas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Promocje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rozpoczecia', models.DateField()),
                ('data_zakonczenia', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wlasciciel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('haslo', models.CharField(max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testER.uzytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='Rezerwacje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('godzina', models.TimeField()),
                ('klient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testER.klient')),
                ('pokoj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testER.pokoj')),
            ],
        ),
        migrations.CreateModel(
            name='Recenzje',
            fields=[
                ('rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('ocena', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('komentarz', models.CharField(blank=True, max_length=500)),
                ('klient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testER.klient')),
                ('pokoj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testER.pokoj')),
            ],
        ),
        migrations.AddField(
            model_name='pokoj',
            name='kat_cenowa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='testER.uzytkownik'),
        ),
        migrations.AddField(
            model_name='pokoj',
            name='promocje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testER.promocje'),
        ),
        migrations.CreateModel(
            name='Odwiedziny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ukonczony', models.BooleanField()),
                ('czas_wyjscia', models.IntegerField()),
                ('data', models.DateField()),
                ('klient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testER.pokoj')),
                ('pokoj_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testER.klient')),
            ],
        ),
        migrations.AddField(
            model_name='klient',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testER.uzytkownik'),
        ),
        migrations.CreateModel(
            name='EscapeRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('adres', models.CharField(max_length=50)),
                ('telefon', models.CharField(max_length=11)),
                ('opis', models.CharField(max_length=500)),
                ('wlasc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testER.wlasciciel')),
            ],
        ),
    ]
