# Generated by Django 4.1.5 on 2023-01-21 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testER', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocje',
            name='procent',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pokoj',
            name='kat_cenowa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='testER.ceny'),
        ),
        migrations.AlterField(
            model_name='pokoj',
            name='promocje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testER.promocje'),
        ),
    ]
