# Generated by Django 4.1.5 on 2023-01-21 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testER', '0002_promocje_procent_alter_pokoj_kat_cenowa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokoj',
            name='firma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testER.escaperoom'),
        ),
    ]
