# Generated by Django 4.1.5 on 2023-01-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testER', '0004_remove_wlasciciel_user_id_alter_escaperoom_wlasc_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escaperoom',
            name='opis',
        ),
        migrations.AddField(
            model_name='pokoj',
            name='opis',
            field=models.CharField(default='brak', max_length=500),
        ),
    ]
