# Generated by Django 4.1.5 on 2023-01-23 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testER', '0006_alter_escaperoom_wlasc_id_alter_odwiedziny_klient_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocje',
            name='data_rozpoczecia',
        ),
        migrations.RemoveField(
            model_name='promocje',
            name='data_zakonczenia',
        ),
    ]
