# Generated by Django 4.1.5 on 2023-01-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testER', '0007_remove_promocje_data_rozpoczecia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocje',
            name='data_rozpoczecia',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='promocje',
            name='data_zakonczenia',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='promocje',
            name='nazwa',
            field=models.CharField(default='promocja', max_length=50),
        ),
    ]
