# Generated by Django 4.1.5 on 2023-01-25 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testER', '0008_promocje_data_rozpoczecia_promocje_data_zakonczenia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odwiedziny',
            name='czas_wyjscia',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='pokoj',
            name='kategoria',
            field=models.CharField(choices=[('P', 'Przygodowy'), ('T', 'Thriller'), ('H', 'Horror'), ('Hi', 'Historyczny'), ('F', 'Fabularny'), ('A', 'Akcja'), ('Fan', 'Fantasy'), ('K', 'Kryminalny')], max_length=40),
        ),
        migrations.AlterField(
            model_name='pokoj',
            name='max_czas',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='pokoj',
            name='trudnosc',
            field=models.CharField(choices=[('Ł', 'Łatwy'), ('Ś', 'Średni'), ('T', 'Trudny')], max_length=10),
        ),
        migrations.AlterField(
            model_name='promocje',
            name='procent',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
