# Generated by Django 4.1.5 on 2023-01-25 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testER', '0009_alter_odwiedziny_czas_wyjscia_alter_pokoj_kategoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odwiedziny',
            name='czas_wyjscia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pokoj',
            name='max_czas',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(60)]),
        ),
    ]
